sudo: false
language: ruby
rvm:
  - 2.4.3
gemfile: "gems.rb"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database bsrc_test;' -U postgres"
  - "rails db:migrate"
